# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb9bfb6d207e419fe826b00b62d237eb3be0db5073829616b93d1e72fe1987c3c9a3fd4530a7a4abe37e983b2fca29594c741e51e90a6c0dec4afa8ae77eccd3

test:
  secret_key_base: dbee6b9f9e305c57de61b0c8c872432dae58823aaf53909c98e4d93893fa91fbf60b1bba11b19e2b601ae2eba3d0cfe9089e2113b66c18f387405cecaa27eeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
